### PR TITLE
A6020: Update Adreno blobs from kipper.

### PR DESCRIPTION
**Pull request by karthick111**
Signed-off-by: karthick111 <karthickrko61@gmail.com>

### CODE REVIEW

**Comment by karthick111** [comment]
This also solve:
1. Auto brightness bug
2. Minor lags and frame drops

**Comment by karthick111** [comment]
@skritchz  have a look at it
we dont need boringssl-compat
i have updated jpeg blobs from kipper
most msm8916 devices did the same
also tested

**Comment by skritchz** [comment]
Ok I'll test that. Right away. Thanks

**Comment by skritchz** [comment]
Can you make the pull request into cm-14.1, if you tested it on this, or was it only tested on cm-13.0?

**Comment by karthick111** [comment]
Tested only on cm-13.0 
For now u can merge it on cm-13.0
I will pull request again with cm-14.1 ,its different from this

**Comment by skritchz** [comment]
Yes I'm doing it, should be fine anyway

**Comment by karthick111** [comment]
i have did it on cm-14.1 branch too

**Comment by Shr3ps** [comment]
Already merged in the up to date branch

**Comment by karthick111** [comment]
This is of cm-13.0 :|

**Pull request closed without merging**
